export { CricketModule } from './cricket.module';
export { FeedIngestService } from './feed-ingest.service';
export type { IngestResult, MarketRepricer } from './feed-ingest.service';
export { CricketRepo } from './cricket.repo';
export { MarketService } from './market.service';
export type { MatchView, MarketView, RunnerView, FancyView } from './market.service';
export { deriveScore, runsInOvers } from './match-state';
export type { MatchScore } from './match-state';
export { priceSessionRuns } from './pricing';
export type { FancyQuote } from './pricing';
export { PlacementService, BetRejectedError } from './placement.service';
export type { PlaceBetInput, PlaceRunnerBetInput } from './placement.service';
export { calculateCustomerExposure, calculateOperatorLiability } from './exposure';
export type { BetPosition } from './exposure';
export { SettlementService, MatchResultError } from './settlement.service';
export type { MarketSettlement, Correction, SettleStatus } from './settlement.service';
export { resolveFancyBet, resolveRunnerBet, sessionRuns, sessionComplete } from './settlement';
export type { SessionOutcome } from './settlement';
